"""Add asking_price to table Player

Revision ID: a57b49111b7e
Revises: 0130c232da99
Create Date: 2022-02-09 04:46:08.580302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57b49111b7e'
down_revision = '0130c232da99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('asking_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'asking_price')
    # ### end Alembic commands ###
